[target.riscv32imac-unknown-none-elf]
rustflags = [
  "-C", "linker=rust-lld", 
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-L",
  "-C", "link-arg=%OUT_DIR%",
  "-C", "link-arg=--nmagic",
]

[target.thumbv7m-none-eabi]
rustflags = [
  "-C", "linker=rust-lld",
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-L",
  "-C", "link-arg=%OUT_DIR%",
  "-C", "link-arg=--nmagic",
]
