[package]
name = "kernel-riscv-minimal"
version = "0.1.0"
edition = "2021"

[workspace]
# Empty workspace to avoid conflicts

[dependencies]
# Minimal RISC-V without riscv-rt for now
panic-halt = "0.2"

[[bin]]
name = "kernel-riscv-minimal"
path = "src/main_debug.rs"
