[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = { version = "0.7", default-features = false, optional = true }
cortex-m-semihosting = { version = "0.5", optional = true }
cortex-m = { version = "0.7", optional = true }
panic-halt = { version = "0.2", optional = true }
riscv-rt = { version = "0.11", optional = true }
riscv = { version = "0.11", optional = true }
nb = { version = "1.0", optional = true }
heapless = { version = "0.8", optional = true }

[features]
arm = ["cortex-m-rt", "cortex-m-semihosting", "cortex-m", "panic-halt", "nb", "heapless"]
riscv = ["riscv-rt", "dep:riscv", "nb", "heapless"]
default = []

[[bin]]
name = "kernel"
path = "src/main.rs"
