//! Build script: generates the module linker script (fixed RAM slot address,
//! per target) and feeds it to rust-lld. Addresses must mirror
//! karatos-kapi (KAPI_ADDR / MODULE_SLOT) — single source of truth enforced
//! by code review + the loader's ABI checks.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let target = env::var("TARGET").expect("TARGET not set");
    // Board defaults per triple; build.sh may override for multi-board
    // triples (e.g. thumbv8m.main -> AN547 geography).
    let (slot, kapi) = if target.starts_with("thumbv8m") {
        (0x3000_4000usize, 0x1001_F000usize)
    } else if target.starts_with("thumb") {
        (0x2000_4000usize, 0x0001_F000usize)
    } else {
        (0x8000_8000usize, 0x8001_0000usize)
    };
    let slot = env::var("KARATOS_MODULE_SLOT").ok()
        .and_then(|v| usize::from_str_radix(v.trim_start_matches("0x"), 16).ok())
        .unwrap_or(slot);
    let kapi = env::var("KARATOS_KAPI_ADDR").ok()
        .and_then(|v| usize::from_str_radix(v.trim_start_matches("0x"), 16).ok())
        .unwrap_or(kapi);

    // Generated address constants consumed by the module source.
    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    fs::write(
        out.join("slot_config.rs"),
        format!("pub const KAPI_ADDR: usize = {kapi:#x};\npub const SLOT_BASE: usize = {slot:#x};\n"),
    )
    .expect("write slot_config.rs");

    let script = out.join("module.x");
    fs::write(
        &script,
        format!(
            r#"/* karatOS loadable module — linked at its fixed RAM slot address.
   Generated by modules/hello/build.rs; do not edit. */

MEMORY {{
    SLOT : ORIGIN = {slot:#x}, LENGTH = 8K
}}

ENTRY(_start)

SECTIONS {{
    . = ORIGIN(SLOT);

    /* Header (32 B, CRC patched post-link) MUST be first in the image. */
    .module.hdr : {{
        KEEP(*(.module.hdr));
    }} > SLOT

    /* Descriptor at offset 32 (karatos-kapi::MODULE_DESC_OFFSET). */
    .module.desc : {{
        KEEP(*(.module.desc));
    }} > SLOT

    .text : {{
        *(.text .text.*);
        *(.rodata .rodata.*);
    }} > SLOT

    .data : {{
        *(.data .data.*);
    }} > SLOT

    /DISCARD/ : {{
        *(.eh_frame .eh_frame.*);
        *(.ARM.exidx .ARM.exidx.*);
        *(.comment);
    }}
}}
"#,
            slot = slot
        ),
    )
    .expect("write module.x");

    println!("cargo:rustc-link-arg=-T{}", script.display());
    println!("cargo:rerun-if-env-changed=KARATOS_MODULE_SLOT");
    println!("cargo:rerun-if-env-changed=KARATOS_KAPI_ADDR");
    println!("cargo:rerun-if-changed=build.rs");
}
