//! ============================================================================
//! MODULE : hello — the first loadable karatOS module (Phase 3 reference)
//! ----------------------------------------------------------------------------
//! PURPOSE
//!   Demonstrates the full extensibility contract:
//!     * linked for a FIXED RAM slot (module.x) — no relocations;
//!     * calls the kernel ONLY via the KAPI table at its fixed address;
//!     * exposes a `#[repr(C)]` descriptor (init/deinit) at image offset 32;
//!     * init() returns OK after printing through the kernel console.
//!
//! BUILD
//!   `cargo build --release --target <triple>` produces an ELF; the build
//!   post-processor (`ci/elf_to_bin.py`) extracts the raw image at the slot
//!   address and patches size + CRC32 into the header. The kernel embeds the
//!   resulting `.bin` and loads it: flash -> verify -> RAM slot -> execute.
//!
//! MEMORY BUDGET
//!   A few hundred bytes of image; the whole thing must fit the 8 kB slot.
//! ============================================================================

#![no_std]
#![no_main]

use karatos_kapi::{
    status, KapiTable, KAPI_ABI_VERSION, MODULE_DESC_MAGIC, MODULE_HEADER_MAGIC,
    ModuleDescriptor, ModuleHeader,
};

// Per-target fixed addresses, generated by build.rs (see karatos-kapi).
include!(concat!(env!("OUT_DIR"), "/slot_config.rs"));

/// This module's CPU (must match the kernel that loads it).
const ARCH_ID: u16 = {
    #[cfg(target_arch = "arm")]
    {
        karatos_kapi::EM_ARM
    }
    #[cfg(any(target_arch = "riscv32", target_arch = "riscv64"))]
    {
        karatos_kapi::EM_RISCV
    }
    // Host builds only ever `cargo check` this crate (modules are built for
    // real targets by build.sh); EM_UNKNOWN keeps the const total.
    #[cfg(not(any(target_arch = "arm", target_arch = "riscv32", target_arch = "riscv64")))]
    {
        0
    }
};

/// Kernel export table at the fixed per-arch address (see karatos-kapi).
const KAPI: *const KapiTable = KAPI_ADDR as *const KapiTable;

/// Console write through the kernel (validates the table first: a module
/// must never trust its environment blindly).
fn console(s: &str) {
    // SAFETY: KAPI points at the kernel's read-only export table.
    let table = unsafe { &*KAPI };
    if table.magic != karatos_kapi::KAPI_TABLE_MAGIC {
        return; // kernel ABI mismatch: stay silent rather than crash
    }
    unsafe { (table.console_write)(s.as_ptr(), s.len()) }
}

/// Module setup — called by the loader after verification.
unsafe extern "C" fn init() -> i32 {
    console("hello module: init() — loaded from flash, running in SRAM\r\n");
    status::OK
}

/// Module teardown — called on retract; SRAM is wiped right after.
unsafe extern "C" fn deinit() {
    console("hello module: deinit() — retracting\r\n");
}

/// Image header (size + CRC patched by the build post-processor).
#[link_section = ".module.hdr"]
#[no_mangle]
pub static MODULE_HEADER: ModuleHeader = ModuleHeader {
    magic: MODULE_HEADER_MAGIC,
    abi_version: KAPI_ABI_VERSION,
    arch: ARCH_ID,
    image_size: 0, // patched post-link
    reserved0: 0,
    crc32: 0, // patched post-link
    reserved: [0; 3],
};

/// The descriptor the kernel locates at image offset 32.
#[link_section = ".module.desc"]
#[no_mangle]
pub static MODULE_DESCRIPTOR: ModuleDescriptor = ModuleDescriptor {
    magic: MODULE_DESC_MAGIC,
    abi_version: KAPI_ABI_VERSION,
    arch: ARCH_ID,
    name: *b"hello\0\0\0\0\0\0\0\0\0\0\0",
    init: Some(init),
    deinit: Some(deinit),
};

/// Link entry stub (module images are never "started", only called into).
#[no_mangle]
pub extern "C" fn _start() -> ! {
    loop {
        core::hint::spin_loop();
    }
}

/// Modules bring their own panic policy (abort = spin here; the kernel's
/// watchdog story covers recovery).
#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    loop {
        core::hint::spin_loop();
    }
}